ERROR [2021-12-01 19:35:41] /mnt/test/bk-itsm/blueapps/account/components/bk_token/backends.py 220 verify_bk_token 8124 140514774906624 
 	 Abnormal error in verify_bk_token... 
Traceback (most recent call last):
  File "/mnt/test/bk-itsm/blueapps/account/components/bk_token/backends.py", line 218, in verify_bk_token
    verify=False)
  File "/mnt/test/bk-itsm/blueapps/account/utils/http.py", line 67, in send
    if response.status_code != requests.codes.ok:
AttributeError: 'NoneType' object has no attribute 'status_code'
ERROR [2021-12-01 19:35:45] /mnt/test/bk-itsm/blueapps/account/components/bk_token/backends.py 220 verify_bk_token 8124 140514774906624 
 	 Abnormal error in verify_bk_token... 
Traceback (most recent call last):
  File "/mnt/test/bk-itsm/blueapps/account/components/bk_token/backends.py", line 218, in verify_bk_token
    verify=False)
  File "/mnt/test/bk-itsm/blueapps/account/utils/http.py", line 67, in send
    if response.status_code != requests.codes.ok:
AttributeError: 'NoneType' object has no attribute 'status_code'
ERROR [2021-12-08 11:24:46] /Users/lidonghui/Desktop/test/mnt/test/bk-itsm/blueapps/account/components/bk_token/backends.py 220 verify_bk_token 1622 123145355882496 
 	 Abnormal error in verify_bk_token... 
Traceback (most recent call last):
  File "/Users/lidonghui/Desktop/test/mnt/test/bk-itsm/blueapps/account/components/bk_token/backends.py", line 217, in verify_bk_token
    response = send(ConfFixture.VERIFY_URL, 'GET', api_params,
  File "/Users/lidonghui/Desktop/test/mnt/test/bk-itsm/blueapps/account/utils/http.py", line 49, in send
    response = session.request(method='GET', url=url, params=params,
  File "/Users/lidonghui/Desktop/test/mnt/test/bk-itsm/requests_tracker/requests/sessions.py", line 88, in request
    prep = self.prepare_request(req)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/login/accounts/is_login/': No schema supplied. Perhaps you meant http:///login/accounts/is_login/?
ERROR [2021-12-08 14:21:29] /Users/lidonghui/Desktop/test/mnt/test/bk-itsm/blueapps/account/components/bk_token/backends.py 220 verify_bk_token 3334 123145484697600 
 	 Abnormal error in verify_bk_token... 
Traceback (most recent call last):
  File "/Users/lidonghui/Desktop/test/mnt/test/bk-itsm/blueapps/account/components/bk_token/backends.py", line 217, in verify_bk_token
    response = send(ConfFixture.VERIFY_URL, 'GET', api_params,
  File "/Users/lidonghui/Desktop/test/mnt/test/bk-itsm/blueapps/account/utils/http.py", line 49, in send
    response = session.request(method='GET', url=url, params=params,
  File "/Users/lidonghui/Desktop/test/mnt/test/bk-itsm/requests_tracker/requests/sessions.py", line 88, in request
    prep = self.prepare_request(req)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/login/accounts/is_login/': No schema supplied. Perhaps you meant http:///login/accounts/is_login/?
ERROR [2021-12-08 15:47:09] /Users/lidonghui/Desktop/test/mnt/test/bk-itsm/blueapps/account/components/bk_token/backends.py 220 verify_bk_token 3831 123145527095296 
 	 Abnormal error in verify_bk_token... 
Traceback (most recent call last):
  File "/Users/lidonghui/Desktop/test/mnt/test/bk-itsm/blueapps/account/components/bk_token/backends.py", line 217, in verify_bk_token
    response = send(ConfFixture.VERIFY_URL, 'GET', api_params,
  File "/Users/lidonghui/Desktop/test/mnt/test/bk-itsm/blueapps/account/utils/http.py", line 49, in send
    response = session.request(method='GET', url=url, params=params,
  File "/Users/lidonghui/Desktop/test/mnt/test/bk-itsm/requests_tracker/requests/sessions.py", line 88, in request
    prep = self.prepare_request(req)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/login/accounts/is_login/': No schema supplied. Perhaps you meant http:///login/accounts/is_login/?
